# !/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Mar 12 15:37:47 2019

@author: python
"""

import warnings
import logging
import operator
from functools import reduce
from abc import ABC, abstractmethod


class TradingControlViolation(Exception):
    """
    Raised if an order would violate a constraint set by a TradingControl.
    """
    msg = """
            {asset} at {datetime} violates trading constraint
            {constraint}.
        """.strip()


class TradingControl(object):
    """
    Abstract base class representing a fail-safe control on the behavior of any
    algorithm.
    """
    def __init__(self,
                 on_error='log',
                 _fail_args='violate_trading_controls'):
        self.on_error = on_error
        self._fail_args = _fail_args

    def validate(self,
                 asset,
                 algo_datetime):
        """
        Before any order is executed by TradingAlgorithm, this method should be
        called *exactly once* on each registered TradingControl object.

        If the specified asset and amount do not violate this TradingControl's
        restraint given the information in `portfolio`, this method should
        return None and have no externally-visible side-effects.

        If the desired order violates this TradingControl's contraint, this
        method should call self.fail(asset, amount).
        """
        raise NotImplementedError("")

    def handle_violation(self,
                         asset,
                         date_time):
        """
        Handle a TradingControlViolation, either by raising or logging and
        error with information about the failure.

        If dynamic information should be displayed as well, pass it in via
        `metadata`.
        """
        constraint = repr(self)

        if self.on_error == 'fail':
            raise TradingControlViolation(
                asset=asset,
                datetime=date_time,
                constraint=constraint)
        elif self.on_error == 'log':
            logging.info("{asset} at {dt} "
                         "violates trading constraint {constraint}",
                         asset=asset, dt=date_time,
                         constraint=constraint)
        elif self.on_error == 'warn':
            warnings.warn("{asset} at {dt} violates trading constraint {constraint}",
                          asset=asset, dt=date_time,
                          constraint=constraint)
        else:
            raise TradingControlViolation(
                asset=asset,
                datetime=date_time,
                constraint=constraint)

    def __repr__(self):
        return "{name}({attrs})".format(name=self.__class__.__name__,
                                        attrs=self._fail_args)

    # def __or__(self, control):
    #     """
    #         Base implementation for combining two restrictions.
    #     """
    #     return reduce(
    #         operator.and_,
    #         (r.validate(asset, algo_datetime) for r in self.controls)
    #     )


class AssetControl(TradingControl):
    """
    Abstract base class representing a fail-safe control on the behavior of any
    algorithm.
    Abstract restricted list interface, representing a set of asset that an
    algorithm is restricted from trading.
    remove asset which trades less than 30 trading_days or delist within 30 trading_days
    """

    def __init__(self, trading_days=30):
        """
        Track any arguments that should be printed in the error message
        generated by self.fail.
        """
        self.window = trading_days
        self.__fail_args = "remove new ipo assets \ delist assets \ suspend assets"

    @abstractmethod
    def validate(self, control_meta):
        """
        On each call to handle data by TradingAlgorithm, this method should be
        called *exactly once* on each registered AccountControl object.

        If the check does not violate this AccountControl's restraint given
        the information in `portfolio` and `account`, this method should
        return None and have no externally-visible side-effects.

        If the desired order violates this AccountControl's contraint, this
        method should call self.fail().
        """
        raise NotImplementedError


# class RiskControl(TradingControl):
#     """
#     control the risk of the position, number of assets in the portfolio / loss of the portfolio
#     """
#     def __init__(self, thres=0.1):
#         self.thres = thres

#     def validate(self, order_meta: OrderMeta, control_meta: ControlMeta):
#         pass


# fuse control


# !/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Mar 12 15:37:47 2019

@author: python
"""
import numpy as np
import operator
from typing import List
from abc import ABC, abstractmethod
from functools import reduce
from collections.abc import Iterable


class Restricted(ABC):
    """
    Abstract restricted list interface, representing a set of asset that an
    algorithm is restricted from trading.
         --- used for pipe which filter asset list
    """

    @abstractmethod
    def is_restricted(self, assets, dt):
        """
        Is the asset restricted (RestrictionStates.FROZEN) on the given dt?

        Parameters
        ----------
        assets : Asset of iterable of Assets
            The asset(s) for which we are querying a restriction
        dt : pd.Timestamp
            The timestamp of the restriction query

        Returns
        -------
        is_restricted : bool or pd.Series[bool] indexed by asset
            Is the asset or asset restricted on this dt?

        """
        raise NotImplementedError('is_restricted')


class NoRestricted(Restricted):
    """
    A no-op restrictions that contains no restrictions.
    """
    def is_restricted(self, assets: List[Asset], dt: int):
        return assets


class Untradeable(Restricted):
    """
        remove suspended or delisted assets on the given dt
        delist_assets:  base on asset delist_date
        suspended_assets: base high-low < epsilon
    """
    def __init__(self, epsilon: float = 0.05):
        self.epsilon = epsilon

    def on_suspended(self, metadata):
        """
            price restricted  high - low < epison
        """
        low = np.min(np.array([item["low"] for item in metadata]))
        high = np.max(np.array([item["high"] for item in metadata]))
        pct = (high - low)/low
        flag = True if pct <= self.p.epsilon else False
        return flag 

    def is_restricted(self, assets, dt):
        assets = assets if isinstance(assets, Iterable) else [assets]
        filter_assets = [asset for asset in assets if asset.delist != 0 and asset.delist > dt]
        filter_assets = [asset for asset in filter_assets if not self.on_suspended(asset.metadata)]
        return filter_assets


class UnionRestricted:
    """
    A union of a number of sub restrictions.

    Parameters
    ----------
    sub_restrictions : iterable of Restrictions (but not _UnionRestrictions)
        The Restrictions to be added together

    Notes
    -----
    - Consumers should not construct instances of this class directly, but
      instead use the `|` operator to combine restrictions
    """

    def __init__(self, restrictions):
        restrictions = restrictions if isinstance(restrictions, Iterable) else [restrictions]
        # Filter out NoRestrictions and deal with resulting cases involving
        # one or zero sub_restrictions
        self.restrictions = [r for r in self.restrictions if not isinstance(r, NoRestricted)]

    def __or__(self, other):
        """
        Overrides the base implementation for combining two restrictions, of
        which the left side is a _UnionRestrictions.
        """
        # Flatten the underlying sub restrictions of _UnionRestrictions
        # If the right side is a _UnionRestrictions, defers to the
        # _UnionRestrictions implementation of `|`, which intelligently
        # flattens restricted lists
        # 调用 _UnionRestrictions 的__or__
        if isinstance(other, UnionRestricted):
            self.restrictions.extend(other.restrictions)
        elif isinstance(other, Restricted):
            self.restrictions.append(other)
        else:
            raise ValueError("Invalid type for restriction")

    # def is_restricted(self, assets, dt):
    #     if isinstance(assets, Asset):
    #         return assets if len(set(r.is_restricted(assets, dt)
    #                                  for r in self.restrictions)) == 1 else None
    #     return reduce(
    #         operator.and_,
    #         (r.is_restricted(assets, dt) for r in self.restrictions)
    #     )
